/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package services.stepin.study.netty.websocket.chat.server;

import io.netty.channel.ChannelFuture;

public class ServetLauncher {

    private final static int DEFAULT_PORT = 8080;

    public static void main(String[] args) throws Exception {

        int port = extractPortFromArgs(args);

        Server server = new Server(port);

        ChannelFuture future = server.start();

        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                server.destroy();
            }
        });

        future.channel().closeFuture().syncUninterruptibly();
    }

    private static int extractPortFromArgs(String[] args){

        return args.length > 0
                ? Integer.parseInt(args[0])
                : DEFAULT_PORT;
    }

}
